services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file: "local.env"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=flightdb'
      - 'POSTGRES_PASSWORD=nopassword'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:7-alpine'
    container_name: case_study-redis-1
    ports:
      - '6379:6379'
