spring:
  application:
    name: case_study
  config:
    import: "optional:file:local.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
jwt:
  secret: afd9da5773cf04bf4fc5ac2a8fcdf433885454e831ff1611f1da7b9ed1fd3a7a
  expiration: 9000