spring:
  application:
    name: case_study
  config:
    import: "optional:file:local.env[.properties]"
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: ${FLYWAY_ENABLED}
    locations: classpath:db/migration, classpath:db/seed
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}