INSERT INTO airports (city, country, iata_code, "name") VALUES
                                                            ('New York', 'USA', 'JFK', 'John F. Kennedy International Airport'),
                                                            ('Los Angeles', 'USA', 'LAX', 'Los Angeles International Airport'),
                                                            ('Chicago', 'USA', 'ORD', 'O''Hare International Airport'),
                                                            ('London', 'UK', 'LHR', 'London Heathrow Airport'),
                                                            ('Paris', 'France', 'CDG', 'Charles de Gaulle Airport'),
                                                            ('Frankfurt', 'Germany', 'FRA', 'Frankfurt Airport'),
                                                            ('Amsterdam', 'Netherlands', 'AMS', 'Amsterdam Airport Schiphol'),
                                                            ('Dubai', 'UAE', 'DXB', 'Dubai International Airport'),
                                                            ('Tokyo', 'Japan', 'HND', 'Tokyo Haneda Airport'),
                                                            ('Sydney', 'Australia', 'SYD', 'Sydney Kingsford Smith Airport'),
                                                            ('Singapore', 'Singapore', 'SIN', 'Singapore Changi Airport'),
                                                            ('Hong Kong', 'China', 'HKG', 'Hong Kong International Airport'),
                                                            ('Istanbul', 'Turkey', 'IST', 'Istanbul Airport'),
                                                            ('Seoul', 'South Korea', 'ICN', 'Incheon International Airport'),
                                                            ('Toronto', 'Canada', 'YYZ', 'Toronto Pearson International Airport'),
                                                            ('Beijing', 'China', 'PEK', 'Beijing Capital International Airport'),
                                                            ('Shanghai', 'China', 'PVG', 'Shanghai Pudong International Airport'),
                                                            ('Bangkok', 'Thailand', 'BKK', 'Suvarnabhumi Airport'),
                                                            ('Mumbai', 'India', 'BOM', 'Chhatrapati Shivaji Maharaj International Airport'),
                                                            ('Delhi', 'India', 'DEL', 'Indira Gandhi International Airport'),
                                                            ('Madrid', 'Spain', 'MAD', 'Adolfo Suárez Madrid–Barajas Airport'),
                                                            ('Rome', 'Italy', 'FCO', 'Leonardo da Vinci–Fiumicino Airport'),
                                                            ('Lisbon', 'Portugal', 'LIS', 'Humberto Delgado Airport'),
                                                            ('Vienna', 'Austria', 'VIE', 'Vienna International Airport'),
                                                            ('Zurich', 'Switzerland', 'ZRH', 'Zurich Airport');