CREATE TABLE public.airports (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 city varchar(255) NOT NULL,
                                 country varchar(255) NOT NULL,
                                 iata_code varchar(3) NOT NULL,
                                 "name" varchar(255) NOT NULL,
                                 CONSTRAINT airports_pkey PRIMARY KEY (id),
                                 CONSTRAINT airports_iata_code_uq UNIQUE (iata_code)
);