CREATE TABLE public.airplanes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	airline varchar(255) NOT NULL,
	capacity int4 NOT NULL,
	model varchar(255) NOT NULL,
	tail_number varchar(255) NOT NULL,
	CONSTRAINT airplanes_capacity_check CHECK ((capacity >= 1)),
	CONSTRAINT airplanes_pkey PRIMARY KEY (id),
	CONSTRAINT airplanes_tail_number_uq UNIQUE (tail_number)
);